apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: front-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "{{ .Values.front_server.host }}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front-server
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "{{ .Values.front_server.host }}"
  gateways:
  - front-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ .Values.front_server.port }}
        host: front-server