# apiVersion: networking.istio.io/v1alpha3
# kind: ServiceEntry
# metadata:
#   name: example
#   namespace: {{ .Release.Namespace }}
# spec:
#   hosts:
#   - certauth.cryptomix.com
#   ports:
#   # - number: 80
#   #   name: http-port
#   #   protocol: HTTP
#   - number: 443
#     name: https
#     protocol: TLS
#   resolution: DNS
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: istio-egressgateway
#   namespace: {{ .Release.Namespace }}
# spec:
#   selector:
#     istio: egressgateway
#   servers:
#   - port:
#       name: https
#       protocol: TLS
#     hosts:
#     - certauth.cryptomix.com
#     tls:
#       mode: MUTUAL
#       credentialName: frontend-certs
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: egressgateway-for-example
#   namespace: {{ .Release.Namespace }}
# spec:
#   host: istio-egressgateway.istio-system.svc.cluster.local
#   subsets:
#   - name: example
#   trafficPolicy:
#     portLevelSettings:
#     - port:
#         number: 443
#       tls:
#         credentialName: frontend-certs
#         mode: MUTUAL
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: direct-example-through-egress-gateway
#   namespace: {{ .Release.Namespace }}
# spec:
#   hosts:
#   - certauth.cryptomix.com
#   # gateways:
#   # - istio-egressgateway
#   # - mesh
#   tls:
#   - match:
#     - sniHosts:
#       - certauth.cryptomix.com
#     route:
#     - destination: 
#         host: istio-egressgateway.istio-system.svc.cluster.local

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: example
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - certauth.cryptomix.com
  ports:
  # - number: 80
  #   name: http-port
  #   protocol: HTTP
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: TLS
    hosts:
    - certauth.cryptomix.com
    tls:
      mode: MUTUAL
      credentialName: frontend-certs
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-example
  namespace: {{ .Release.Namespace }}
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: example
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-example-through-egress-gateway
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - certauth.cryptomix.com
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 443
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: example
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
    route:
    - destination:
        host: certauth.cryptomix.com
        port:
          number: 443
      weight: 100
