apiVersion: v1
kind: Service
metadata:
  name: front-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: front-server
  ports:
  - port: {{ .Values.front_server.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.front_server.replicas }}
  selector:
    matchLabels:
      app: front-server
  template:
    metadata:
      labels:
        app: front-server
    spec:
      containers:
      - name: front
        image: {{ .Values.front_server.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.front_server.port }}
          name: front
        env:
        - name: BACK_SERVER_URL
          value: {{ .Values.front_server.env.back_server_url }}
